calibration_node:
  ros__parameters:
    cmd_rate: 20
    encoder_rate: 30
    max_lin_speed: 2.0
    max_ang_speed: 2.0
    step_len: 6.0
    n_calib_steps: 10
    dead_man_button: True
    dead_man_index: 5
    dead_man_threshold: 0.7
    ramp_trigger_button: False
    ramp_trigger_index: 7
    calib_trigger_button: False
    calib_trigger_index: 7
    load_input_space_calib_data: False
    path_to_input_space_calib_data: "/home/robot/workspaces/marmotte_ws/src/doughnut_calib/calib_data/marmotte/input_space_data_mw.pkl"
