doughnut_calib_node:
  ros__parameters:
    wheel_radius: 0.3
    robot_baseline: 1.08
    ramp_gain: 0.05
    cmd_rate: 20
    encoder_rate: 30
    max_lin_speed: 5.0
    min_lin_speed: 0.0
    lin_speed_step: 0.5
    max_ang_speed: 5.0
    ang_steps: 8
    step_len: 6.0
    dead_man_button: False
    dead_man_index: 5
    dead_man_threshold: -500.0
    ramp_trigger_button: True
    ramp_trigger_index: 0                                                                                                                             
    calib_trigger_button: True                                                                                                                       
    calib_trigger_index: 2                                                                                                                            
    steady_state_window: 1.5                                                                                                                          
    steady_state_std_dev_threshold: 0.5                                                                                                               
    n_uniform_samples: 25                                                                                                                             
    load_input_space_calib_data: False                                                                                                                
    run_random_validation: False                                                                                                                      
    path_to_input_space_calib_data: "/home/robot/workspaces/marmotte_ws/src/doughnut_calib/calib_data/marmotte/input_space_data_mw.pkl"
