rate: 20

max_lin_speed: 4.0
min_lin_speed: 2.0
lin_speed_step: 1.0

max_ang_speed: 6.0
ang_steps: 10
step_len: 1.0

dead_man_index: 5
dead_man_threshold: 0.7

ramp_trigger_index: 1
calib_trigger_index: 1

steady_state_window: 1.5
steady_state_std_dev_threshold: 0.5

