/**: 
  calibration_node:
    ros__parameters:
      command_model: 'differential_drive'
      auto_max_speed_characterization: True
      auto_cmd_model_characterization: False
      wheel_radius: 0.165
      wheel_baseline: 0.55
      cmd_rate: 20
      encoder_rate: 7
      max_lin_speed: 2.0
      max_ang_speed: 2.0
      step_len: 6.0
      n_calib_steps: 2
      dead_man_button: True
      dead_man_index: 5
      dead_man_threshold: 0.7
      calib_trigger_button: False
      calib_trigger_index: 7
      calib_threshold: 0.7
      record_wheel_current: False
      record_wheel_voltage: False
      type_of_encoder: 'JointState'
      left_wheel_encoder_velocity_index: 2
      right_wheel_encoder_velocity_index: 3
