/drive/calibration_node:
  ros__parameters:
    cmd_rate: 20
    encoder_rate: 4
    max_lin_speed: 5.0
    max_ang_speed: 4.0
    step_len: 6.0
    dead_man_button: false
    dead_man_index: 5
    dead_man_threshold: -500.0
    ramp_trigger_button: true
    ramp_trigger_index: 2
    calib_trigger_button: true
    calib_trigger_index: 2
    auto_cmd_model_characterization: false
    auto_max_speed_characterization: false
    n_calib_steps: 100
    path_to_save_input_space_calib: /home/robot/ros2_ws/src/DRIVE/calib_data/test_warthog/input_space_data_mw.pkl
    wheel_radius: 0.3
    wheel_baseline: 1.08
    run_by_maestro: true
source_of_this_file: /home/robot/ros2_ws/src/DRIVE/calib_data/warthog_wheels_ice_2024_7_30_16h30s21_ice_param
