/drive/logger_node:
  ros__parameters:
    record_wheel_current: true
    record_wheel_voltage: true
    run_by_maestro: true
source_of_this_file: /home/robot/ros2_ws/src/DRIVE/calib_data/warthog_wheels_gravel_2024_8_6_11h37s32
